apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myrn
  template:
    metadata:
      labels:
        app: myrn
    spec:
      containers:
      - name: myrn
        image: patrickoceandigital/reactnginx
        imagePullPolicy: Always  
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: secretdockerhub

---
apiVersion: v1
kind: Service
metadata:
  name: myrn
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: myrn
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myrn
            port:
              number: 80
