version: '3'
services:
  reactapp:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
        - ./my-app:/usr/src/app/my-app
        - /usr/src/app/my-app/node_modules
    env_file:     
    - ./frontend/.envod
    #environment:    #comment this if you want to env_file to be used
    #- REACT_APP_API_URL=netflix.com
